user:
  #username 学号或者工号
  username: 161105024
  #password 密码，用不到，原因是：login.py获取不到MOD_AUTH_CAS
  password: '161105024'
  #address 地址，定位信息
  address: 中国四川省成都市金牛区一环路北1段-129号-附9号
  #email 接受通知消息的邮箱
  email: 461009747@qq.com
  #lon 当前位置经度，可以访问http://zuobiao.ay800.com/s/27/index.php获取
  lon: '119.191475'
  #lat 当前位置纬度
  lat: '26.058264'
  #school 学校全称
  school: 福州大学
#今日校园相关配置
cpdaily:
  #表单组默认选项配置
  defaults:
    #表单默认选项配置，按顺序，注意，只有标必填项的才处理，不会配置就执行generate.py
    - default:
        title: 今日所在位置
        type: 1
        value: 福建省/漳州市/芗城区
    - default:
        title: 昨日午检体温
        type: 2
        value: 小于37.3度
    - default:
        title: 今日晨检体温
        type: 2
        value: 小于37.3度
    - default:
        title: 今日健康状况（可多选）
        type: 3
        value: 健康，无症状
    - default:
        title: 家庭成员是否有确诊感染、疑似感染新冠肺炎患者或无症状感染者
        type: 2
        value: 否
    - default:
        title: 今日是否为入院状态（入院指生病住院）
        type: 2
        value: 否
    - default:
        title: 目前是否为新冠肺炎确诊/疑似病例或无症状感染者（若选“是“，必须已与就诊医生确认）
        type: 2
        value: 否
    - default:
        title: 今日隔离情况
        type: 2
        value: 无需隔离
    - default:
        title: 今日是否因与确诊病人有密切接触，被当地强制隔离中
        type: 2
        value: 否
    - default:
        title: 今日是否因有发热、咳嗽、乏力、呼吸困难等疑似症状在隔离中
        type: 2
        value: 否
    - default:
        title: 近14日以来，你接触过疫情重点地区流出人员或确诊/疑似新冠肺炎患者等情况
        type: 2
        value: 无此类情况
    - default:
        title: 近14日以来，你居住、旅行、途经疫情重点地区情况
        type: 2
        value: 无此类情况
    - default:
        title: 是否在今日入闽
        type: 2
        value: 否
    - default:
        title: 住址是否在今日有变动
        type: 2
        value: 否
    - default:
        title: 近14日以来，你的共同居住者（包括家庭成员、共同租住人员、共同居住房东家庭成员）有无以下特殊情况（可多选）
        type: 3
        value: 无以下特殊情况
    - default:
        title: 本人承诺以上所填报的全部内容均属实、准确，不存在任何隐瞒与不实的情况，更无遗漏之处。
        type: 2
        value: 是